# Dockerfile.elasticsearch

FROM docker.elastic.co/elasticsearch/elasticsearch:7.13.4

# Establecer variables de entorno necesarias
ENV node.name=elasticsearch
ENV cluster.name=docker-cluster
ENV discovery.type=single-node
ENV bootstrap.memory_lock=true
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false

# Establecer límites de memoria
RUN ulimit -l unlimited
