# railway.toml

[services.elasticsearch]
  build = "./Dockerfile.elasticsearch"
  run = "docker run --name elasticsearch -p 9200:9200 elasticsearch"

[services.kibana]
  build = "./Dockerfile.kibana"
  run = "docker run --name kibana -p 5601:5601 kibana"
